name: Generate Snake Animation

on:
  schedule:
    # Runs automatically every day at midnight UTC
    - cron: "0 0 * * *"
  
  # Allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Jinsiya
          # Generates a snake animation from your contribution graph
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
          
      - name: Push to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          # Keeps only the latest version
          force_orphan: true
